name: Elevators
version: 5.0.0
author: Keehl
main: com.lkeehl.elevators.Elevators
api-version: 1.13
loadbefore: [SuperiorSkyblock2]
softdepend: [PlaceholderAPI,RedProtect,Vault,HolographicDisplays,GriefPrevention,GriefDefender,CMI,PlotSquared,BentoBox,DecentHolograms,FancyHolograms,ProtocolLib]

commands:
  elevators:
    description: Access elevators commands
    usage: /elevators
    aliases: [ele]