name: Elevators
author: Keehl
main: me.keehl.elevators.ElevatorsPlugin
api-version: 1.13
folia-supported: true
loadbefore: [SuperiorSkyblock2]
softdepend: [PlaceholderAPI,RedProtect,Vault,HolographicDisplays,GriefPrevention,GriefDefender,CMI,PlotSquared,BentoBox,DecentHolograms,FancyHolograms,ProtocolLib,WorldGuard]

commands:
  elevators:
    description: Access elevators commands
    usage: /elevators
    aliases: [ele]
version: 5.0.0-beta.11